### ISSUE TITLE
Question on FlorisQ() function

### ISSUE THREAD

**Issue by Bartdoekemeijer** [TUDelft-DataDrivenControl/FLORISSE_M#6]
Hi,

Just looking through the code, I find in _floris_compute_windspeed.m_:
 
```
function Q = FlorisQ()
        Q   = turbines(dw_turbi).rotorArea;
        wakeOverlapTurb = [0 0 0];
        for zone = 1:3
           wakeOverlapTurb(zone) = floris_intersect(wakes(uw_turbi).rZones(deltax,zone),turbines(dw_turbi).rotorRadius,...
             hypot(turbines(dw_turbi).LocWF(2)-(wakes(uw_turbi).centerLine(2,turbLocIndex)),...
                   turbines(dw_turbi).LocWF(3)-(wakes(uw_turbi).centerLine(3,turbLocIndex))));

           for zonej = 1:(zone-1) % minus overlap areas of lower zones
               wakeOverlapTurb(zone) = wakeOverlapTurb(zone)-wakeOverlapTurb(zonej);
           end
           Q = Q - 2*turbines(uw_turbi).axialInd*wakes(uw_turbi).cZones(deltax,zone)*wakeOverlapTurb(zone);
        end
    end
```

which refers to the right term within the brackets of:
![image](https://user-images.githubusercontent.com/22119448/35616357-52f8d5c4-0675-11e8-95a1-9770970e1b47.png)
if I am correct. The current implementation sums the wake zones linearly, while the paper presents a root-sum-square method. I find the same issue in the Python version from NREL. Is this on purpose, am I missing something?

**Comment by Bartdoekemeijer** [comment]
Never mind, figured it out! Closed.

**Comment by RmStorm** [comment]
Actually the Q term is only the inner summation. There are two summations in this expressions. The inner sum sums over the wake zones to compute the predicted velocity deficit of upwind turbine i. The outer one sums over all the turbines, i -> n, to combine the wakes of all upwind turbines.

This wake combining can be done in several different ways. The one used in the original paper does a sum of square of the wake deficit of each turbine.

I see that this issue is closed now but I still wanted to post the explanation in case someone else finds this someday.
